### ISSUE TITLE
Support --component (-c) to create a root comopnent

### ISSUE THREAD

**Issue by sthzg** [sthzg/contrib-subgen-react-webpack-container#2]
``` sh
react-webpack:container foo --component
# Creates Foo.js and FooContainer.js. FooContainer.js renders <Foo/>

react-webpack:container foo --component bar
# Creates Bar.js and FooContainer.js. FooContainer.js renders <Bar/>
```

**Todos**
- [x] Create container and component files
- [x] Make container import and render component
- [x] Modify generated test for container component
